import React from 'react';

export const About = () => {
  return (
    <div
      color="white"
      style={{
        backgroundColor: "rgba(255, 255, 255, 0.5)",
        fontWeight: "bold",
      }}
    >
      <p>THIS IS AN ABOUT COMPONENT</p>
      <p>THIS IS JESSICA.... AND THIS WEBSITE IS BROUGHT TO YOU BY A NERDY MELANCHOLIC GEEK :)</p>
      <p>THIS IS A SIMPLE TODO LIST APPLICATION BUILT USING REACT JS.</p>
      <p>IT ALLOWS USERS TO ADD, DELETE, AND VIEW THEIR TASKS EASILY.</p>
      <p>THE APPLICATION IS DESIGNED TO BE USER-FRIENDLY AND EFFICIENT.</p>
      <p>IT UTILIZES COMPONENT-BASED ARCHITECTURE FOR BETTER MAINTENANCE AND SCALABILITY.</p>
      <p>THE UI IS SIMPLE AND CLEAN, MAKING IT EASY FOR USERS TO NAVIGATE.</p>
      <p>THE APPLICATION IS RESPONSIVE AND WORKS WELL ON BOTH DESKTOP AND MOBILE DEVICES.</p>
      <p>THE CODE IS WRITTEN IN A MODULAR FASHION, ALLOWING FOR EASY UPDATES AND IMPROVEMENTS.</p>
      <p>OVERALL, THIS TODO LIST APPLICATION IS A GREAT TOOL FOR ANYONE LOOKING TO STAY ORGANIZED AND PRODUCTIVE.</p>
      <p>IT IS A GREAT EXAMPLE OF HOW REACT JS CAN BE USED TO BUILD FUNCTIONAL AND ATTRACTIVE WEB APPLICATIONS.</p>
      <p>THANK YOU FOR USING THIS APPLICATION!</p>
    </div>
  );
};
